-- return {
--   'renerocksai/telekasten.nvim',
--   dependencies = { 'nvim-telescope/telescope.nvim', 'renerocksai/calendar-vim' },
--   opts = {
--     home = vim.fn.expand '~/notes',
--   },
--   init = function()
--     vim.keymap.set('n', '<leader>z', '<cmd>Telekasten panel<CR>', { noremap = true, silent = true, desc = 'Open Telekasten panel' })
--   end,
-- }
return {}
